$(document).ready(function(){
    $(".owl-carousel").owlCarousel();
});

$('.owl-carousel').owlCarousel({
    loop:true,
    margin:5,
    responsiveClass:true,
    responsive:{
        0:{
            items:7,
            nav:true
        },
        600:{
            items:8,
            nav:false
        },
        1000:{
            items:8,
            nav:true,
            loop:false
        }
    }
})